apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: if76o7f3p-nodejs 
  janus-idp.io/tekton: if76o7f3p-nodejs
  backstage.io/kubernetes-id: if76o7f3p-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: if76o7f3p-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  