apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: if76o7f3p-nodejs
  janus-idp.io/tekton: if76o7f3p-nodejs
  backstage.io/kubernetes-id: if76o7f3p-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: if76o7f3p-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
