apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: if76o7f3p-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: if76o7f3p-nodejs 
  name: if76o7f3p-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: if76o7f3p-nodejs 
